// angular-ui/src/app/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from "@angular/router";
import { FormBuilder, FormGroup } from '@angular/forms';
import { api } from '../../services/api';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {

  loginForm: FormGroup;

  constructor(private router: Router, private fb: FormBuilder) {
    this.loginForm = this.fb.group({
      email: fb.control(''),
      password: fb.control('')
    })
  }

  userLoggedIn: any = localStorage.getItem('username');

  ngOnInit(): void {
    if(this.userLoggedIn) {
      this.router.navigate(['/dashboard']);
    }
  }

  async onSubmit(e: Event) {
    e.preventDefault();
    const data = this.loginForm.value;
    await api.login_service.login(data)
    .then((resp: any) => {
      localStorage.setItem("username", resp.email);
    })
    .catch(err => {
      const errorMsg: any = document.getElementById("error");
      errorMsg.style.display = "inline";
    })

    await api.login_service.authenticate({username: data.email, password: data.password})
      .then((data: any) => {
        if(data.token != null) {
          localStorage.setItem("token", data.token);
          this.router.navigate(["/dashboard"])
        }
      });
  }

}

<app-navbar></app-navbar>
<div class="login-container">
  <form [formGroup]="loginForm" (ngSubmit)="onSubmit($event);">
  <div class="login-form">
      <div class="title">
          <h1>Login</h1>
      </div>
      <div class="form">
      <span id="error">Incorrect email or password. Please try again. </span>
          <div class="input">
              <div class="field">
                  <div class="email-icon">＠</div>
                  <input formControlName="email" name="email" type="text" placeholder="Email" required />
              </div>
          </div>
          <div class="input">
              <div class="field">
                  <div class="password-icon">🔑</div>
                  <input formControlName="password" name="password" type="password" placeholder="Password" required />
              </div>
          </div>
          <button id="submit-btn" type="submit">Submit</button>
      </div>
  </div>
</form>
</div>

// react-ui/src/components/Login.jsx
import React, { useState } from 'react';
import { useHistory } from 'react-router-dom';
import '../styles/login/login.css';

export default function Login(props) {
    const {state} = props;
    const [loginState, setLoginState] = useState({"email": "", "password": ""});
    const history = useHistory();

    const handleChange = e => {
        const { name, value } = e.target;
        setLoginState(prevState => ({...prevState, [name]: value}))
    }

    const onSubmit = e => {
        props.login(loginState)
        .catch(err => {
            const errorMsg = document.getElementById("error");
            errorMsg.style.display = "inline";
        })
        setTimeout(() => {
            history.push("/dashboard")
        }, 500);
    }

    return (
        <>
            {state.username.length > 0 ? (
                history.push("/dashboard")
            ) : (
                <div class="login-container">
                    <div class="login-form">
                        <div class="title">
                            <h1>Login</h1>
                        </div>
                        <div class="form">
                        <span id="error">Incorrect email or password. Please try again. </span>
                            <div class="input">
                                <div class="field">
                                    <div class="email-icon">＠</div>
                                    <input name="email" type="text" placeholder="Email" required />
                                </div>
                            </div>
                            <div class="input">
                                <div class="field">
                                    <div class="password-icon">🔑</div>
                                    <input name="password" type="password" placeholder="Password" required />
                                </div>
                            </div>
                            <button onClick={onSubmit} id="submit-btn" type="submit">Submit</button>
                        </div>
                    </div>
                </div>
            )}
        </>
        
    )
}
