// react-ui/src/components/employees/EmployeeEdit.jsx
import React, { useEffect, useState } from 'react';
import validation from '../validation.js';
import { useHistory } from 'react-router-dom';
import { api } from '../../services/api.js';
import '../../styles/employee/employee.css';

export default function EmployeeEdit(props) {
    const ID = props.match.url.split("/")[2];
    const [employee, setEmployee] = useState([]);
    const [errors, setErrors] = useState();
    const history = useHistory();
    
    useEffect(() => {
        api.employee_service.employeeById(ID)
        .then(data => setEmployee(data));
    }, [ID]);

    const handleChange = e => {
        const { name, value } = e.target;
        setErrors(prevState => ({...prevState, [name]: ""}));
        setEmployee(prevState => ({...prevState, [name]: value }));
    }

    const handleConfirmChanges = () => {
        const err = validation(employee);
        setErrors(err)

        if(Object.keys(err).length > 0) {
            return null;
        } else {
            api.employee_service.updateEmployee(employee)
            .then(resp => console.log(resp));
            
            setTimeout(() => {
                history.push("/employee/all");
            }, 500);
        };
    };

    const handleDelete = () => {
        api.employee_service.deleteEmployee(employee)
        .then(resp => console.log(resp))
        .then(
            setTimeout(() => {
                history.push("/employee/all")
            }, 500)
        );
    };

    const returnToList = () => {
        history.push("/employee/all");
    };

    return (
        <div class="form_container">
            <h1>{employee.firstName + " " + employee.lastName} -- UID: {employee.userId}  </h1>
            <div class="edit__form">
                <div class="title">
                    <h1>Edit</h1>
                </div>
                <div class="rows">
                    <div class="row">
                        <div class="input">
                            <label for="firstName">First Name</label>
                            <input name="firstName" value={employee.firstName == null ? "" : employee.firstName}/>
                            <p class="errors">{errors?.firstName}</p>
                        </div>
                        <div class="input">
                            <label for="lastName">Last Name</label>
                            <input name="lastName" value={employee.lastName == null ? "" : employee.lastName} />
                            <p class="errors">{errors?.lastName}</p>
                        </div>
                        <div class="input">
                            <label for="email">Email</label>
                            <input name="email" value={employee.email == null ? "" : employee.email} />
                            <p class="errors">{errors?.email}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input">
                            <label for="address">Address</label>
                            <input name="address" value={employee.address == null ? "" : employee.address} />
                            <p class="errors">{errors?.address}</p>
                        </div>
                        <div class="input">
                            <label for="city">City</label>
                            <input name="city" value={employee.city == null ? "" : employee.city} />
                            <p class="errors">{errors?.city}</p>
                        </div>
                        <div class="input">
                            <label for="state">State</label>
                            <select name="state" id="state">
                                <option defaultValue={employee.state}>{employee.state}</option>
                                <option value="Alabama">Alabama</option>
                                <option value="Alaska">Alaska</option>
                                <option value="Arizona">Arizona</option>
                                <option value="Arkansas">Arkansas</option>
                                <option value="California">California</option>
                                <option value="Colorado">Colorado</option>
                                <option value="Connecticut">Connecticut</option>
                                <option value="Delaware">Delaware</option>
                                <option value="Florida">Florida</option>
                                <option value="Georgia">Georgia</option>
                                <option value="Hawaii">Hawaii</option>
                                <option value="Idaho">Idaho</option>
                                <option value="Illinois">Illinois</option>
                                <option value="Indiana">Indiana</option>
                                <option value="Iowa">Iowa</option>
                                <option value="Kansas">Kansas</option>
                                <option value="Kentucky">Kentucky</option>
                                <option value="Louisiana">Louisiana</option>
                                <option value="Maine">Maine</option>
                                <option value="Maryland">Maryland</option>
                                <option value="Massachusetts">Massachusetts</option>
                                <option value="Michigan">Michigan</option>
                                <option value="Minnesota">Minnesota</option>
                                <option value="Mississippi">Mississippi</option>
                                <option value="Missouri">Missouri</option>
                                <option value="Montana">Montana</option>
                                <option value="Nebraska">Nebraska</option>
                                <option value="Nevada">Nevada</option>
                                <option value="New Hampshire">New Hampshire</option>
                                <option value="New Jersey">New Jersey</option>
                                <option value="New Mexico">New Mexico</option>
                                <option value="New York">New York</option>
                                <option value="North Carolina">North Carolina</option>
                                <option value="Ohio">Ohio</option>
                                <option value="Oklahoma">Oklahoma</option>
                                <option value="Oregon">Oregon</option>
                                <option value="Pennsylvania">Pennsylvania</option>
                                <option value="Rhode Island">Rhode Island</option>
                                <option value="South Carolina">South Carolina</option>
                                <option value="South Dakota">South Dakota</option>
                                <option value="Tennessee">Tennessee</option>
                                <option value="Texas">Texas</option>
                                <option value="Utah">Utah</option>
                                <option value="Vermont">Vermont</option>
                                <option value="Virginia">Virginia</option>
                                <option value="Washington">Washington</option>
                                <option value="West Virginia">West Virginia</option>
                                <option value="Wisconsin">Wisconsin</option>
                                <option value="Wyoming">Wyoming</option>
                                {/* <option value="Alabama">Alabama</option> */}
                            </select>
                            <p class="errors">{errors?.state}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="input">
                            <label for="zip">Zip Code</label>
                            <input name="zip" value={employee.zip == null ? "" : employee.zip} />
                            <p class="errors">{errors?.zip}</p>
                        </div>
                        <div class="input">
                            <label for="cellPhone">Cell Phone</label>
                            <input name="cellPhone" value={employee.cellPhone == null ? "" : employee.cellPhone} />
                            <p class="errors">{errors?.cellPhone}</p>
                        </div>
                        <div class="input">
                            <label for="homePhone">Home Phone</label>
                            <input name="homePhone" value={employee.homePhone == null ? "" : employee.homePhone} />
                            <p class="errors">{errors?.homePhone}</p>
                        </div>
                    </div>
                    <div class="choices">
                        <button onClick={handleConfirmChanges} id="confirm_changes_btn" type="submit">Confirm Changes</button>
                        <button onClick={handleDelete} id="delete_btn" type="submit">Delete Employee</button>
                    </div>
        
                </div>
            </div>
            <button onClick={returnToList} id="list_return_btn">Back to list</button>
        </div>
    )
}

// angular-ui/src/app/employees/employee-edit/employee-edit.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';
import { ActivatedRoute, Params, Router } from '@angular/router';
import { api } from 'src/services/api';
import { EmployeeObj } from '../employee.model';

@Component({
  selector: 'app-employee-edit',
  templateUrl: './employee-edit.component.html',
  styleUrls: ['./employee-edit.component.scss']
})
export class EmployeeEditComponent implements OnInit {

  employeeForm: FormGroup;

  public id!: number;
  employeeObject: EmployeeObj[] = [{
    id: 0,
    firstName: '',
    lastName: '',
    address: '',
    city: '',
    state: '',
    zip: '',
    cellPhone: '',
    homePhone: '',
    email: '',
    userId: ''
  }];
  public auth: boolean = false;

  constructor(private fb: FormBuilder, private router: Router, private route: ActivatedRoute) {
    this.employeeForm = this.fb.group({
        id: fb.control(''),
        userId: fb.control(''),
        firstName: fb.control(''),
        lastName: fb.control(''),
        email: fb.control(''),
        address: fb.control(''),
        city: fb.control(''),
        state: fb.control(''),
        zip: fb.control(''),
        cellPhone: fb.control(''),
        homePhone: fb.control('')
      });
  };

  async ngOnInit(): Promise<void> {
    // Set the param id
    this.route.params.subscribe((params: Params) => {
      this.id = params['id'];
    });

    // Authenticate me & then fetch employee
    this.authenticateMe()
    .then(await this.getEmployee(this.id))
    .then(resp => console.log(this.employeeObject))
    console.log("AFTER ASYNC", this.employeeObject);

    // Set employee values in the form
    this.employeeForm.patchValue({
      id: this.employeeObject[0].id,
      userId: this.employeeObject[0].userId,
      firstName: this.employeeObject[0].firstName,
      lastName: this.employeeObject[0].lastName,
      email: this.employeeObject[0].email,
      address: this.employeeObject[0].address,
      city: this.employeeObject[0].city,
      zip: this.employeeObject[0].zip,
      state: this.employeeObject[0].state,
      cellPhone: this.employeeObject[0].cellPhone,
      homePhone: this.employeeObject[0].homePhone
    })

    console.log("EMP FORM", this.employeeForm.value)
  }

  getEmployee(id: number) {
    return api.employee_service.employeeById(id)
    .then(resp => this.employeeObject[0] = resp)
  }

  async authenticateMe() {
    return await api.login_service.authcheck()
    .then(resp => {
        if(resp.status) {
          this.auth = true;
        }
    }).catch(err => {
      if(!this.auth) {
        localStorage.clear();
        this.router.navigate(['/login']);
      }
    })
  }

  confirmChanges(): Promise<any> {
    return api.employee_service.updateEmployee(this.employeeForm.value)
          .then(resp => console.log(resp))
  }

  deleteEmployee(): Promise<any> {
    return api.employee_service.deleteEmployee(this.employeeForm.value)
          .then(resp => console.log(resp))
          .then(resp => this.router.navigate(['/employee']))
  }

}

<app-navbar-loggedin></app-navbar-loggedin>
<div class="form_container" *ngFor="let employee of employeeObject">
  <h1>{{employee.firstName}} {{employee.lastName}} -- UID: {{employee.userId}}  </h1>
  <div class="edit__form">
      <div class="title">
          <h1>Edit</h1>
      </div>
      <form [formGroup]="employeeForm" *ngFor="let employee of employeeObject">
        <div class="rows">
          <div class="row">
              <div class="input">
                  <label for="firstName">First Name</label>
                  <input formControlName="firstName" name="firstName" value={{employee.firstName}}/>
                  <p class="errors"></p>
              </div>
              <div class="input">
                  <label for="lastName">Last Name</label>
                  <input formControlName="lastName"name="lastName" value={{employee.lastName}} />
                  <p class="errors"></p>
              </div>
              <div class="input">
                  <label for="email">Email</label>
                  <input formControlName="email" name="email" value={{employee.email}} />
                  <p class="errors"></p>
              </div>
          </div>
          <div class="row">
              <div class="input">
                  <label for="address">Address</label>
                  <input formControlName="address" name="address" value={{employee.address}} />
                  <p class="errors"></p>
              </div>
              <div class="input">
                  <label for="city">City</label>
                  <input formControlName="city" name="city" value={{employee.city}} />
                  <p class="errors"></p>
              </div>
              <div class="input">
                  <label for="state">State</label>
                  <select formControlName="state" name="state" id="state">
                      <option selected={{employee.state}}>{{employee.state}}</option>
                      <option value="Alabama">Alabama</option>
                      <option value="Alaska">Alaska</option>
                      <option value="Arizona">Arizona</option>
                      <option value="Arkansas">Arkansas</option>
                      <option value="California">California</option>
                      <option value="Colorado">Colorado</option>
                      <option value="Connecticut">Connecticut</option>
                      <option value="Delaware">Delaware</option>
                      <option value="Florida">Florida</option>
                      <option value="Georgia">Georgia</option>
                      <option value="Hawaii">Hawaii</option>
                      <option value="Idaho">Idaho</option>
                      <option value="Illinois">Illinois</option>
                      <option value="Indiana">Indiana</option>
                      <option value="Iowa">Iowa</option>
                      <option value="Kansas">Kansas</option>
                      <option value="Kentucky">Kentucky</option>
                      <option value="Louisiana">Louisiana</option>
                      <option value="Maine">Maine</option>
                      <option value="Maryland">Maryland</option>
                      <option value="Massachusetts">Massachusetts</option>
                      <option value="Michigan">Michigan</option>
                      <option value="Minnesota">Minnesota</option>
                      <option value="Mississippi">Mississippi</option>
                      <option value="Missouri">Missouri</option>
                      <option value="Montana">Montana</option>
                      <option value="Nebraska">Nebraska</option>
                      <option value="Nevada">Nevada</option>
                      <option value="New Hampshire">New Hampshire</option>
                      <option value="New Jersey">New Jersey</option>
                      <option value="New Mexico">New Mexico</option>
                      <option value="New York">New York</option>
                      <option value="North Carolina">North Carolina</option>
                      <option value="Ohio">Ohio</option>
                      <option value="Oklahoma">Oklahoma</option>
                      <option value="Oregon">Oregon</option>
                      <option value="Pennsylvania">Pennsylvania</option>
                      <option value="Rhode Island">Rhode Island</option>
                      <option value="South Carolina">South Carolina</option>
                      <option value="South Dakota">South Dakota</option>
                      <option value="Tennessee">Tennessee</option>
                      <option value="Texas">Texas</option>
                      <option value="Utah">Utah</option>
                      <option value="Vermont">Vermont</option>
                      <option value="Virginia">Virginia</option>
                      <option value="Washington">Washington</option>
                      <option value="West Virginia">West Virginia</option>
                      <option value="Wisconsin">Wisconsin</option>
                      <option value="Wyoming">Wyoming</option>
                  </select>
                  <p class="errors"></p>
              </div>
          </div>
          <div class="row">
              <div class="input">
                  <label for="zip">Zip Code</label>
                  <input formControlName="zip" name="zip" value={{employee.zip}} />
                  <p class="errors"></p>
              </div>
              <div class="input">
                  <label for="cellPhone">Cell Phone</label>
                  <input formControlName="cellPhone" name="cellPhone" value={{employee.cellPhone}} />
                  <p class="errors"></p>
              </div>
              <div class="input">
                  <label for="homePhone">Home Phone</label>
                  <input formControlName="homePhone" name="homePhone" value={{employee.homePhone}} />
                  <p class="errors"></p>
              </div>
          </div>
          <div class="choices">
              <button (click)="confirmChanges();" id="confirm_changes_btn" type="submit">Confirm Changes</button>
              <button (click)="deleteEmployee();" id="delete_btn" type="submit">Delete Employee</button>
          </div>

      </div>
      </form>
  </div>
  <a href="/employee"><button id="list_return_btn">Back to list</button></a>
</div>
